### PR TITLE
Add CircleCI. Closes GH-31

### PR DESCRIPTION
**Pull request by deathcap**
https://github.com/voxel/voxel-clientmc/issues/31

### CODE REVIEW

**Comment by deathcap** [comment]
Getting this mysterious error from browserify on CircleCI - never seen this locally..

```
./app/node_modules/.bin/browserify app/app.js > app/wsmc/src/main/resources/www/bundle.js
Error: Cannot find module 'app/node_modules/browserify/node_modules/insert-module-globals/node_modules/is-buffer/index.js' from '/home/ubuntu/voxel-clientmc'
  at /home/ubuntu/voxel-clientmc/app/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
  at process (/home/ubuntu/voxel-clientmc/app/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
  at ondir (/home/ubuntu/voxel-clientmc/app/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
  at load (/home/ubuntu/voxel-clientmc/app/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
  at onex (/home/ubuntu/voxel-clientmc/app/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
  at /home/ubuntu/voxel-clientmc/app/node_modules/browserify/node_modules/resolve/lib/async.js:22:47

./app/node_modules/.bin/browserify app/app.js > app/wsmc/src/main/resources/www/bundle.js returned exit code 1

at FSReqWrap.oncomplete (fs.js:82:15) Action failed: ./app/node_modules/.bin/browserify app/app.js > app/wsmc/src/main/resources/www/bundle.js
```

**Comment by deathcap** [comment]
http://stackoverflow.com/questions/21685044/browserify-uncaught-error-cannot-find-module-in-bundle-js says this occurs when using a jison parser, sure enough https://github.com/rom1504/node-mojangson uses jison, but only as a dev dependency? Maybe its something else. The stackoverflow user says they fixed it in their case by "replacing that mindfuck exports part with a exports.parser = parser;"

**Comment by deathcap** [comment]
There are differences in `npm ls` on voxel-clientmc/app, on my local system and circleci: https://gist.github.com/deathcap/1e530528e8fb3ae0d67b - mainly minor/patch version bumps

**Comment by rom1504** [comment]
@deathcap I think I found your problem, the published grammar.js seems to still contain the cli thingy. republishing it in a bit.

**Comment by deathcap** [comment]
@rom1504 cool thanks. reproduced locally was about to track it down =)

**Comment by rom1504** [comment]
fixed in mojangson 0.2.3
just rerun circle ci (possibly without cache, not sure how it handle npm cache) and that should do it.

**Comment by deathcap** [comment]
Updated and verified circleci is using mojangson 0.2.3 which has the main stub as expected:

```javascript
exports.main = function (){};
```

so I think the problem with mojagson is fixed. Still getting this error though - maybe another problematic unbrowserifiable module:

```
voxel-clientmc $ ./app/node_modules/.bin/browserify app/app.js > app/wsmc/src/main/resources/www/bundle.js
Error: Cannot find module 'app/node_modules/is-buffer/index.js' from '/private/tmp/vc/voxel-clientmc'
  at /private/tmp/vc/voxel-clientmc/app/node_modules/resolve/lib/async.js:46:17
  at process (/private/tmp/vc/voxel-clientmc/app/node_modules/resolve/lib/async.js:173:43)
  at ondir (/private/tmp/vc/voxel-clientmc/app/node_modules/resolve/lib/async.js:188:17)
  at load (/private/tmp/vc/voxel-clientmc/app/node_modules/resolve/lib/async.js:69:43)
  at onex (/private/tmp/vc/voxel-clientmc/app/node_modules/resolve/lib/async.js:92:31)
  at /private/tmp/vc/voxel-clientmc/app/node_modules/resolve/lib/async.js:22:47
  at FSReqWrap.oncomplete (fs.js:82:15)
```

ill need to isolate further..

**Pull request merged**
